name: example
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'
dependencies: 
  cupertino_icons: ^1.0.2
  fluttercontactpicker: ^4.7.0
  fluttertoast: ^8.1.1
  select_card: ^0.0.9
  flutter_json_view: ^1.0.0
  get: ^4.6.5
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_lints: ^2.0.0
  pubspec_dependency_sorter: ^0.0.2
  flutter_test: 
    sdk: flutter
  sasapay_sdk: 
    path: ../
flutter: 
  assets: 
    - assets/images/
  uses-material-design: true
